### ISSUE TITLE
Replace scss-lint by sass-lint

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/sphynx#656]
Right now we're loading `gulp-scss-lint` which requires us to have `scss_lint` installed. This is a Ruby Gem, so our package cannot specify it's version. Right now we often have conflicts, because not every developer uses the latest version.

[Sass-lint](https://github.com/sasstools/sass-lint) is a tool that works on pure Node.js. There is also [a Gulp plugin](https://www.npmjs.com/package/gulp-sass-lint) for it.

Probably could use some research on differences and linting preferences (i.e. the `scss.yml` file we use right now).

**Comment by luukdv** [comment]
Good stuff. If we can make it work the same way with our preferred config (http://sass-guidelin.es/#scss-lint - I don't see why not), let's do it.

**Comment by sboerrigter** [comment]
I'll close this in favour of https://github.com/trendwerk/sphynx/issues/794
