### ISSUE TITLE
Rename `output/` folder to `dist/`

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/sphynx#767]
A bit more descriptive than 'output' (could be any output).

**Comment by sboerrigter** [comment]
I agree. Maybe we should also move the `/dist` folder out of the `/assets` folder.

**Comment by sboerrigter** [comment]
@haroldangenent Why don't you agree with moving the `dist` folder out of the `assets` folder? Popular frameworks like Laravel also use a seperate folder for their `public` files. Makes sense to me. Can you please explain?

And do you prefer `dist` or `public` for the folder name?

**Comment by haroldangenent** [comment]
@sboerrigter I believe `public/` (in most frameworks) is used as a webroot (not for compiled assets), which wouldn't be the case for a WordPress theme. So I think that naming would be a bit confusing. `dist/` isn't really accurate either, but I prefer it over `public/`.

Moving the dist assets in another folder than the source files wouldn't make a lot of sense to me (I don't see any advantages). Right now, dist files are not in a shared folder as well (they are written out in a folder next to the source files) and I don't really see any point in investing time to change this.

That being said, this seems like an opinionated choice and I don't really care about it.
