### ISSUE TITLE
Maybe remove medium_large size

### ISSUE THREAD

**Issue by luukdv** [trendwerk/sphynx#781]
In `4.4.0`, WP added the `medium_large` size (768px). This one isn't used, but does take up server space. Should we remove it by default?

**Comment by luukdv** [comment]
Additional information:

https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/#post-15628 (the 'A new default image size' part)

**Comment by sboerrigter** [comment]
I don't understand why this has been added if it is only available for developers. Developers can always add image sizes when it is needed. Let's remove it.
