### ISSUE TITLE
Update documentation with info about Yarn

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/sphynx#783]
This page still contains info about Bower instead of Yarn: https://github.com/trendwerk/sphynx/wiki/Development-tools

**Comment by luukdv** [comment]
Related: https://github.com/trendwerk/sphynx/issues/754

**Comment by sboerrigter** [comment]
Or NPM5? https://github.com/trendwerk/sphynx/issues/785

**Comment by luukdv** [comment]
Yes, let's close this one.
