### ISSUE TITLE
Remove underscores from .sass files.

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/sphynx#788]
I prefer to remove the leading underscores from Sass files and instruct Gulp to only compile `main.scss` and `editor.scss`. This makes the file structure cleaner and prevents errors with forgotten underscores.

**Comment by haroldangenent** [comment]
I feel that disregarding Sass' own guidelines wouldn't be a good choice for a framework / starter theme.

**Comment by luukdv** [comment]
Disagreed, for the same reason. The underscores are also handy for lookup, and have special meaning (they're not compiled to an output file for example).
