### ISSUE TITLE
Rename `respond-to` mixin to `breakpoint`.

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/sphynx#791]
I think the name `breakpoint` makes more sense.

**Comment by luukdv** [comment]
I'm using this mixin a _lot_, and I think it benefits from a name that is as short as possible. Although `respond-to` is better (more expressive), my votes goes to `break`.

**Comment by sboerrigter** [comment]
Maybe we could also use `min-width` and `max-width`?

**Comment by luukdv** [comment]
I think `@media(min-width: map-get($breakpoints, 'medium')) {` is too verbose, shall we stick to a mixin?

**Comment by sboerrigter** [comment]
That is wheat I meant. For example: `@include min-width('medium');`.
