### ISSUE TITLE
Faster compile process ⚡️

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/sphynx#794]
Name says it all. How could we achieve this?

For example, I'm all for removing a bunch of tools.

**Comment by luukdv** [comment]
Agreed, it's _way_ too slow right now. Idea's:

- Remove the lint police (especially SCSS, we know best practices by now)
- Prefix less browsers (#784)
- Drop Fancybox as a default dep so the `base64` task can be removed
- Run development builds unless specified. Minification, for example, is not necessary during development
- Remove welcome message, `colors` dependency
- Remove globbing (:trollface:)
- Switch to Rollup/Webpack/Broccoli if compilation speed differs much from Gulp

**Comment by sboerrigter** [comment]
Are you serious about removing globbing or is it just to troll? I agree with the rest of the suggestions.

**Comment by luukdv** [comment]
I thought it was pretty obvious with the trollface and all ;)

**Comment by haroldangenent** [comment]
Agree with all the things, let's keep only the essentials for development. Perhaps move some code-quality stuff to a separate build or test process.

> Switch to Rollup/Webpack/Broccoli if compilation speed differs much from Gulp

Switching to Webpack would allow tasks like `base64` (which would also be needed for Photoswipe, for example) to be removed as well, since Webpack resolves those files if I'm correct. I'm very much in favor of stepping away from Gulp.

> Remove the lint police

Also for ESLint and PHP CS in my opinion, especially on each file save. Most linters could also be implemented in your code editor, if you prefer.

**Comment by luukdv** [comment]
Good idea about separate tasks. Regarding the resolving of files in Webpack, we can add the following to prevent this:

```
use: [{
  loader: 'css-loader',
  options: { url: false },
}],
```

**Comment by haroldangenent** [comment]
_Note: When dropping all linters, README can be heavily simplified._
